/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'
import { Route as DashboardWarehouseRouteImport } from './routes/_dashboard/warehouse/route'
import { Route as DashboardProductionRouteImport } from './routes/_dashboard/production/route'
import { Route as DashboardCustomersRouteImport } from './routes/_dashboard/customers/route'
import { Route as DashboardBasicInfoRouteImport } from './routes/_dashboard/basic-info/route'
import { Route as DashboardProductionIndexImport } from './routes/_dashboard/production/index'
import { Route as DashboardWarehouseStockedImport } from './routes/_dashboard/warehouse/stocked'
import { Route as DashboardWarehousePurchasesImport } from './routes/_dashboard/warehouse/purchases'
import { Route as DashboardWarehouseOrdersImport } from './routes/_dashboard/warehouse/orders'
import { Route as DashboardWarehouseConsumedImport } from './routes/_dashboard/warehouse/consumed'
import { Route as DashboardWarehouseCertificatesImport } from './routes/_dashboard/warehouse/certificates'
import { Route as DashboardCustomersCreateImport } from './routes/_dashboard/customers/create'
import { Route as DashboardBasicInfoCompanyInfoImport } from './routes/_dashboard/basic-info/company-info'
import { Route as DashboardCustomersSummaryIndexImport } from './routes/_dashboard/customers/summary/index'
import { Route as DashboardBasicInfoEmployeesIndexImport } from './routes/_dashboard/basic-info/employees/index'
import { Route as DashboardProductionCustomerIdProjectIdImport } from './routes/_dashboard/production/$customerId/$projectId'
import { Route as DashboardBasicInfoErpPermissionsUsersImport } from './routes/_dashboard/basic-info/erp-permissions/users'
import { Route as DashboardBasicInfoErpPermissionsRolesImport } from './routes/_dashboard/basic-info/erp-permissions/roles'
import { Route as DashboardBasicInfoErpPermissionsDepartmentsImport } from './routes/_dashboard/basic-info/erp-permissions/departments'
import { Route as DashboardBasicInfoErpPermissionsDepartmentMembersImport } from './routes/_dashboard/basic-info/erp-permissions/department-members'
import { Route as DashboardBasicInfoErpPermissionsAppMachinePermissionsImport } from './routes/_dashboard/basic-info/erp-permissions/app-machine-permissions'
import { Route as DashboardBasicInfoEmployeesCreateImport } from './routes/_dashboard/basic-info/employees/create'
import { Route as DashboardCustomersSummaryCustomerIdIndexImport } from './routes/_dashboard/customers/summary/$customerId/index'
import { Route as DashboardBasicInfoEmployeesEmployeeIdIndexImport } from './routes/_dashboard/basic-info/employees/$employeeId/index'
import { Route as DashboardCustomersSummaryCustomerIdProjectsIndexImport } from './routes/_dashboard/customers/summary/$customerId/projects/index'
import { Route as DashboardCustomersSummaryCustomerIdProjectsCreateImport } from './routes/_dashboard/customers/summary/$customerId/projects/create'
import { Route as DashboardCustomersSummaryCustomerIdProjectsProjectIdImport } from './routes/_dashboard/customers/summary/$customerId/projects/$projectId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardWarehouseRouteRoute = DashboardWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProductionRouteRoute = DashboardProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCustomersRouteRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardBasicInfoRouteRoute = DashboardBasicInfoRouteImport.update({
  id: '/basic-info',
  path: '/basic-info',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProductionIndexRoute = DashboardProductionIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProductionRouteRoute,
} as any)

const DashboardWarehouseStockedRoute = DashboardWarehouseStockedImport.update({
  id: '/stocked',
  path: '/stocked',
  getParentRoute: () => DashboardWarehouseRouteRoute,
} as any)

const DashboardWarehousePurchasesRoute =
  DashboardWarehousePurchasesImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => DashboardWarehouseRouteRoute,
  } as any)

const DashboardWarehouseOrdersRoute = DashboardWarehouseOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardWarehouseRouteRoute,
} as any)

const DashboardWarehouseConsumedRoute = DashboardWarehouseConsumedImport.update(
  {
    id: '/consumed',
    path: '/consumed',
    getParentRoute: () => DashboardWarehouseRouteRoute,
  } as any,
)

const DashboardWarehouseCertificatesRoute =
  DashboardWarehouseCertificatesImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => DashboardWarehouseRouteRoute,
  } as any)

const DashboardCustomersCreateRoute = DashboardCustomersCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardCustomersRouteRoute,
} as any)

const DashboardBasicInfoCompanyInfoRoute =
  DashboardBasicInfoCompanyInfoImport.update({
    id: '/company-info',
    path: '/company-info',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardCustomersSummaryIndexRoute =
  DashboardCustomersSummaryIndexImport.update({
    id: '/summary/',
    path: '/summary/',
    getParentRoute: () => DashboardCustomersRouteRoute,
  } as any)

const DashboardBasicInfoEmployeesIndexRoute =
  DashboardBasicInfoEmployeesIndexImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardProductionCustomerIdProjectIdRoute =
  DashboardProductionCustomerIdProjectIdImport.update({
    id: '/$customerId/$projectId',
    path: '/$customerId/$projectId',
    getParentRoute: () => DashboardProductionRouteRoute,
  } as any)

const DashboardBasicInfoErpPermissionsUsersRoute =
  DashboardBasicInfoErpPermissionsUsersImport.update({
    id: '/erp-permissions/users',
    path: '/erp-permissions/users',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardBasicInfoErpPermissionsRolesRoute =
  DashboardBasicInfoErpPermissionsRolesImport.update({
    id: '/erp-permissions/roles',
    path: '/erp-permissions/roles',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardBasicInfoErpPermissionsDepartmentsRoute =
  DashboardBasicInfoErpPermissionsDepartmentsImport.update({
    id: '/erp-permissions/departments',
    path: '/erp-permissions/departments',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardBasicInfoErpPermissionsDepartmentMembersRoute =
  DashboardBasicInfoErpPermissionsDepartmentMembersImport.update({
    id: '/erp-permissions/department-members',
    path: '/erp-permissions/department-members',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute =
  DashboardBasicInfoErpPermissionsAppMachinePermissionsImport.update({
    id: '/erp-permissions/app-machine-permissions',
    path: '/erp-permissions/app-machine-permissions',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardBasicInfoEmployeesCreateRoute =
  DashboardBasicInfoEmployeesCreateImport.update({
    id: '/employees/create',
    path: '/employees/create',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardCustomersSummaryCustomerIdIndexRoute =
  DashboardCustomersSummaryCustomerIdIndexImport.update({
    id: '/summary/$customerId/',
    path: '/summary/$customerId/',
    getParentRoute: () => DashboardCustomersRouteRoute,
  } as any)

const DashboardBasicInfoEmployeesEmployeeIdIndexRoute =
  DashboardBasicInfoEmployeesEmployeeIdIndexImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => DashboardBasicInfoRouteRoute,
  } as any)

const DashboardCustomersSummaryCustomerIdProjectsIndexRoute =
  DashboardCustomersSummaryCustomerIdProjectsIndexImport.update({
    id: '/summary/$customerId/projects/',
    path: '/summary/$customerId/projects/',
    getParentRoute: () => DashboardCustomersRouteRoute,
  } as any)

const DashboardCustomersSummaryCustomerIdProjectsCreateRoute =
  DashboardCustomersSummaryCustomerIdProjectsCreateImport.update({
    id: '/summary/$customerId/projects/create',
    path: '/summary/$customerId/projects/create',
    getParentRoute: () => DashboardCustomersRouteRoute,
  } as any)

const DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute =
  DashboardCustomersSummaryCustomerIdProjectsProjectIdImport.update({
    id: '/summary/$customerId/projects/$projectId',
    path: '/summary/$customerId/projects/$projectId',
    getParentRoute: () => DashboardCustomersRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/basic-info': {
      id: '/_dashboard/basic-info'
      path: '/basic-info'
      fullPath: '/basic-info'
      preLoaderRoute: typeof DashboardBasicInfoRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/customers': {
      id: '/_dashboard/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/production': {
      id: '/_dashboard/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof DashboardProductionRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/warehouse': {
      id: '/_dashboard/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof DashboardWarehouseRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_dashboard/basic-info/company-info': {
      id: '/_dashboard/basic-info/company-info'
      path: '/company-info'
      fullPath: '/basic-info/company-info'
      preLoaderRoute: typeof DashboardBasicInfoCompanyInfoImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/customers/create': {
      id: '/_dashboard/customers/create'
      path: '/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof DashboardCustomersCreateImport
      parentRoute: typeof DashboardCustomersRouteImport
    }
    '/_dashboard/warehouse/certificates': {
      id: '/_dashboard/warehouse/certificates'
      path: '/certificates'
      fullPath: '/warehouse/certificates'
      preLoaderRoute: typeof DashboardWarehouseCertificatesImport
      parentRoute: typeof DashboardWarehouseRouteImport
    }
    '/_dashboard/warehouse/consumed': {
      id: '/_dashboard/warehouse/consumed'
      path: '/consumed'
      fullPath: '/warehouse/consumed'
      preLoaderRoute: typeof DashboardWarehouseConsumedImport
      parentRoute: typeof DashboardWarehouseRouteImport
    }
    '/_dashboard/warehouse/orders': {
      id: '/_dashboard/warehouse/orders'
      path: '/orders'
      fullPath: '/warehouse/orders'
      preLoaderRoute: typeof DashboardWarehouseOrdersImport
      parentRoute: typeof DashboardWarehouseRouteImport
    }
    '/_dashboard/warehouse/purchases': {
      id: '/_dashboard/warehouse/purchases'
      path: '/purchases'
      fullPath: '/warehouse/purchases'
      preLoaderRoute: typeof DashboardWarehousePurchasesImport
      parentRoute: typeof DashboardWarehouseRouteImport
    }
    '/_dashboard/warehouse/stocked': {
      id: '/_dashboard/warehouse/stocked'
      path: '/stocked'
      fullPath: '/warehouse/stocked'
      preLoaderRoute: typeof DashboardWarehouseStockedImport
      parentRoute: typeof DashboardWarehouseRouteImport
    }
    '/_dashboard/production/': {
      id: '/_dashboard/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof DashboardProductionIndexImport
      parentRoute: typeof DashboardProductionRouteImport
    }
    '/_dashboard/basic-info/employees/create': {
      id: '/_dashboard/basic-info/employees/create'
      path: '/employees/create'
      fullPath: '/basic-info/employees/create'
      preLoaderRoute: typeof DashboardBasicInfoEmployeesCreateImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/basic-info/erp-permissions/app-machine-permissions': {
      id: '/_dashboard/basic-info/erp-permissions/app-machine-permissions'
      path: '/erp-permissions/app-machine-permissions'
      fullPath: '/basic-info/erp-permissions/app-machine-permissions'
      preLoaderRoute: typeof DashboardBasicInfoErpPermissionsAppMachinePermissionsImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/basic-info/erp-permissions/department-members': {
      id: '/_dashboard/basic-info/erp-permissions/department-members'
      path: '/erp-permissions/department-members'
      fullPath: '/basic-info/erp-permissions/department-members'
      preLoaderRoute: typeof DashboardBasicInfoErpPermissionsDepartmentMembersImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/basic-info/erp-permissions/departments': {
      id: '/_dashboard/basic-info/erp-permissions/departments'
      path: '/erp-permissions/departments'
      fullPath: '/basic-info/erp-permissions/departments'
      preLoaderRoute: typeof DashboardBasicInfoErpPermissionsDepartmentsImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/basic-info/erp-permissions/roles': {
      id: '/_dashboard/basic-info/erp-permissions/roles'
      path: '/erp-permissions/roles'
      fullPath: '/basic-info/erp-permissions/roles'
      preLoaderRoute: typeof DashboardBasicInfoErpPermissionsRolesImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/basic-info/erp-permissions/users': {
      id: '/_dashboard/basic-info/erp-permissions/users'
      path: '/erp-permissions/users'
      fullPath: '/basic-info/erp-permissions/users'
      preLoaderRoute: typeof DashboardBasicInfoErpPermissionsUsersImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/production/$customerId/$projectId': {
      id: '/_dashboard/production/$customerId/$projectId'
      path: '/$customerId/$projectId'
      fullPath: '/production/$customerId/$projectId'
      preLoaderRoute: typeof DashboardProductionCustomerIdProjectIdImport
      parentRoute: typeof DashboardProductionRouteImport
    }
    '/_dashboard/basic-info/employees/': {
      id: '/_dashboard/basic-info/employees/'
      path: '/employees'
      fullPath: '/basic-info/employees'
      preLoaderRoute: typeof DashboardBasicInfoEmployeesIndexImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/customers/summary/': {
      id: '/_dashboard/customers/summary/'
      path: '/summary'
      fullPath: '/customers/summary'
      preLoaderRoute: typeof DashboardCustomersSummaryIndexImport
      parentRoute: typeof DashboardCustomersRouteImport
    }
    '/_dashboard/basic-info/employees/$employeeId/': {
      id: '/_dashboard/basic-info/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/basic-info/employees/$employeeId'
      preLoaderRoute: typeof DashboardBasicInfoEmployeesEmployeeIdIndexImport
      parentRoute: typeof DashboardBasicInfoRouteImport
    }
    '/_dashboard/customers/summary/$customerId/': {
      id: '/_dashboard/customers/summary/$customerId/'
      path: '/summary/$customerId'
      fullPath: '/customers/summary/$customerId'
      preLoaderRoute: typeof DashboardCustomersSummaryCustomerIdIndexImport
      parentRoute: typeof DashboardCustomersRouteImport
    }
    '/_dashboard/customers/summary/$customerId/projects/$projectId': {
      id: '/_dashboard/customers/summary/$customerId/projects/$projectId'
      path: '/summary/$customerId/projects/$projectId'
      fullPath: '/customers/summary/$customerId/projects/$projectId'
      preLoaderRoute: typeof DashboardCustomersSummaryCustomerIdProjectsProjectIdImport
      parentRoute: typeof DashboardCustomersRouteImport
    }
    '/_dashboard/customers/summary/$customerId/projects/create': {
      id: '/_dashboard/customers/summary/$customerId/projects/create'
      path: '/summary/$customerId/projects/create'
      fullPath: '/customers/summary/$customerId/projects/create'
      preLoaderRoute: typeof DashboardCustomersSummaryCustomerIdProjectsCreateImport
      parentRoute: typeof DashboardCustomersRouteImport
    }
    '/_dashboard/customers/summary/$customerId/projects/': {
      id: '/_dashboard/customers/summary/$customerId/projects/'
      path: '/summary/$customerId/projects'
      fullPath: '/customers/summary/$customerId/projects'
      preLoaderRoute: typeof DashboardCustomersSummaryCustomerIdProjectsIndexImport
      parentRoute: typeof DashboardCustomersRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardBasicInfoRouteRouteChildren {
  DashboardBasicInfoCompanyInfoRoute: typeof DashboardBasicInfoCompanyInfoRoute
  DashboardBasicInfoEmployeesCreateRoute: typeof DashboardBasicInfoEmployeesCreateRoute
  DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute: typeof DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute
  DashboardBasicInfoErpPermissionsDepartmentMembersRoute: typeof DashboardBasicInfoErpPermissionsDepartmentMembersRoute
  DashboardBasicInfoErpPermissionsDepartmentsRoute: typeof DashboardBasicInfoErpPermissionsDepartmentsRoute
  DashboardBasicInfoErpPermissionsRolesRoute: typeof DashboardBasicInfoErpPermissionsRolesRoute
  DashboardBasicInfoErpPermissionsUsersRoute: typeof DashboardBasicInfoErpPermissionsUsersRoute
  DashboardBasicInfoEmployeesIndexRoute: typeof DashboardBasicInfoEmployeesIndexRoute
  DashboardBasicInfoEmployeesEmployeeIdIndexRoute: typeof DashboardBasicInfoEmployeesEmployeeIdIndexRoute
}

const DashboardBasicInfoRouteRouteChildren: DashboardBasicInfoRouteRouteChildren =
  {
    DashboardBasicInfoCompanyInfoRoute: DashboardBasicInfoCompanyInfoRoute,
    DashboardBasicInfoEmployeesCreateRoute:
      DashboardBasicInfoEmployeesCreateRoute,
    DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute:
      DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute,
    DashboardBasicInfoErpPermissionsDepartmentMembersRoute:
      DashboardBasicInfoErpPermissionsDepartmentMembersRoute,
    DashboardBasicInfoErpPermissionsDepartmentsRoute:
      DashboardBasicInfoErpPermissionsDepartmentsRoute,
    DashboardBasicInfoErpPermissionsRolesRoute:
      DashboardBasicInfoErpPermissionsRolesRoute,
    DashboardBasicInfoErpPermissionsUsersRoute:
      DashboardBasicInfoErpPermissionsUsersRoute,
    DashboardBasicInfoEmployeesIndexRoute:
      DashboardBasicInfoEmployeesIndexRoute,
    DashboardBasicInfoEmployeesEmployeeIdIndexRoute:
      DashboardBasicInfoEmployeesEmployeeIdIndexRoute,
  }

const DashboardBasicInfoRouteRouteWithChildren =
  DashboardBasicInfoRouteRoute._addFileChildren(
    DashboardBasicInfoRouteRouteChildren,
  )

interface DashboardCustomersRouteRouteChildren {
  DashboardCustomersCreateRoute: typeof DashboardCustomersCreateRoute
  DashboardCustomersSummaryIndexRoute: typeof DashboardCustomersSummaryIndexRoute
  DashboardCustomersSummaryCustomerIdIndexRoute: typeof DashboardCustomersSummaryCustomerIdIndexRoute
  DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute: typeof DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute
  DashboardCustomersSummaryCustomerIdProjectsCreateRoute: typeof DashboardCustomersSummaryCustomerIdProjectsCreateRoute
  DashboardCustomersSummaryCustomerIdProjectsIndexRoute: typeof DashboardCustomersSummaryCustomerIdProjectsIndexRoute
}

const DashboardCustomersRouteRouteChildren: DashboardCustomersRouteRouteChildren =
  {
    DashboardCustomersCreateRoute: DashboardCustomersCreateRoute,
    DashboardCustomersSummaryIndexRoute: DashboardCustomersSummaryIndexRoute,
    DashboardCustomersSummaryCustomerIdIndexRoute:
      DashboardCustomersSummaryCustomerIdIndexRoute,
    DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute:
      DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute,
    DashboardCustomersSummaryCustomerIdProjectsCreateRoute:
      DashboardCustomersSummaryCustomerIdProjectsCreateRoute,
    DashboardCustomersSummaryCustomerIdProjectsIndexRoute:
      DashboardCustomersSummaryCustomerIdProjectsIndexRoute,
  }

const DashboardCustomersRouteRouteWithChildren =
  DashboardCustomersRouteRoute._addFileChildren(
    DashboardCustomersRouteRouteChildren,
  )

interface DashboardProductionRouteRouteChildren {
  DashboardProductionIndexRoute: typeof DashboardProductionIndexRoute
  DashboardProductionCustomerIdProjectIdRoute: typeof DashboardProductionCustomerIdProjectIdRoute
}

const DashboardProductionRouteRouteChildren: DashboardProductionRouteRouteChildren =
  {
    DashboardProductionIndexRoute: DashboardProductionIndexRoute,
    DashboardProductionCustomerIdProjectIdRoute:
      DashboardProductionCustomerIdProjectIdRoute,
  }

const DashboardProductionRouteRouteWithChildren =
  DashboardProductionRouteRoute._addFileChildren(
    DashboardProductionRouteRouteChildren,
  )

interface DashboardWarehouseRouteRouteChildren {
  DashboardWarehouseCertificatesRoute: typeof DashboardWarehouseCertificatesRoute
  DashboardWarehouseConsumedRoute: typeof DashboardWarehouseConsumedRoute
  DashboardWarehouseOrdersRoute: typeof DashboardWarehouseOrdersRoute
  DashboardWarehousePurchasesRoute: typeof DashboardWarehousePurchasesRoute
  DashboardWarehouseStockedRoute: typeof DashboardWarehouseStockedRoute
}

const DashboardWarehouseRouteRouteChildren: DashboardWarehouseRouteRouteChildren =
  {
    DashboardWarehouseCertificatesRoute: DashboardWarehouseCertificatesRoute,
    DashboardWarehouseConsumedRoute: DashboardWarehouseConsumedRoute,
    DashboardWarehouseOrdersRoute: DashboardWarehouseOrdersRoute,
    DashboardWarehousePurchasesRoute: DashboardWarehousePurchasesRoute,
    DashboardWarehouseStockedRoute: DashboardWarehouseStockedRoute,
  }

const DashboardWarehouseRouteRouteWithChildren =
  DashboardWarehouseRouteRoute._addFileChildren(
    DashboardWarehouseRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardBasicInfoRouteRoute: typeof DashboardBasicInfoRouteRouteWithChildren
  DashboardCustomersRouteRoute: typeof DashboardCustomersRouteRouteWithChildren
  DashboardProductionRouteRoute: typeof DashboardProductionRouteRouteWithChildren
  DashboardWarehouseRouteRoute: typeof DashboardWarehouseRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBasicInfoRouteRoute: DashboardBasicInfoRouteRouteWithChildren,
  DashboardCustomersRouteRoute: DashboardCustomersRouteRouteWithChildren,
  DashboardProductionRouteRoute: DashboardProductionRouteRouteWithChildren,
  DashboardWarehouseRouteRoute: DashboardWarehouseRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/basic-info': typeof DashboardBasicInfoRouteRouteWithChildren
  '/customers': typeof DashboardCustomersRouteRouteWithChildren
  '/production': typeof DashboardProductionRouteRouteWithChildren
  '/warehouse': typeof DashboardWarehouseRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/basic-info/company-info': typeof DashboardBasicInfoCompanyInfoRoute
  '/customers/create': typeof DashboardCustomersCreateRoute
  '/warehouse/certificates': typeof DashboardWarehouseCertificatesRoute
  '/warehouse/consumed': typeof DashboardWarehouseConsumedRoute
  '/warehouse/orders': typeof DashboardWarehouseOrdersRoute
  '/warehouse/purchases': typeof DashboardWarehousePurchasesRoute
  '/warehouse/stocked': typeof DashboardWarehouseStockedRoute
  '/production/': typeof DashboardProductionIndexRoute
  '/basic-info/employees/create': typeof DashboardBasicInfoEmployeesCreateRoute
  '/basic-info/erp-permissions/app-machine-permissions': typeof DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute
  '/basic-info/erp-permissions/department-members': typeof DashboardBasicInfoErpPermissionsDepartmentMembersRoute
  '/basic-info/erp-permissions/departments': typeof DashboardBasicInfoErpPermissionsDepartmentsRoute
  '/basic-info/erp-permissions/roles': typeof DashboardBasicInfoErpPermissionsRolesRoute
  '/basic-info/erp-permissions/users': typeof DashboardBasicInfoErpPermissionsUsersRoute
  '/production/$customerId/$projectId': typeof DashboardProductionCustomerIdProjectIdRoute
  '/basic-info/employees': typeof DashboardBasicInfoEmployeesIndexRoute
  '/customers/summary': typeof DashboardCustomersSummaryIndexRoute
  '/basic-info/employees/$employeeId': typeof DashboardBasicInfoEmployeesEmployeeIdIndexRoute
  '/customers/summary/$customerId': typeof DashboardCustomersSummaryCustomerIdIndexRoute
  '/customers/summary/$customerId/projects/$projectId': typeof DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute
  '/customers/summary/$customerId/projects/create': typeof DashboardCustomersSummaryCustomerIdProjectsCreateRoute
  '/customers/summary/$customerId/projects': typeof DashboardCustomersSummaryCustomerIdProjectsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/basic-info': typeof DashboardBasicInfoRouteRouteWithChildren
  '/customers': typeof DashboardCustomersRouteRouteWithChildren
  '/warehouse': typeof DashboardWarehouseRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/basic-info/company-info': typeof DashboardBasicInfoCompanyInfoRoute
  '/customers/create': typeof DashboardCustomersCreateRoute
  '/warehouse/certificates': typeof DashboardWarehouseCertificatesRoute
  '/warehouse/consumed': typeof DashboardWarehouseConsumedRoute
  '/warehouse/orders': typeof DashboardWarehouseOrdersRoute
  '/warehouse/purchases': typeof DashboardWarehousePurchasesRoute
  '/warehouse/stocked': typeof DashboardWarehouseStockedRoute
  '/production': typeof DashboardProductionIndexRoute
  '/basic-info/employees/create': typeof DashboardBasicInfoEmployeesCreateRoute
  '/basic-info/erp-permissions/app-machine-permissions': typeof DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute
  '/basic-info/erp-permissions/department-members': typeof DashboardBasicInfoErpPermissionsDepartmentMembersRoute
  '/basic-info/erp-permissions/departments': typeof DashboardBasicInfoErpPermissionsDepartmentsRoute
  '/basic-info/erp-permissions/roles': typeof DashboardBasicInfoErpPermissionsRolesRoute
  '/basic-info/erp-permissions/users': typeof DashboardBasicInfoErpPermissionsUsersRoute
  '/production/$customerId/$projectId': typeof DashboardProductionCustomerIdProjectIdRoute
  '/basic-info/employees': typeof DashboardBasicInfoEmployeesIndexRoute
  '/customers/summary': typeof DashboardCustomersSummaryIndexRoute
  '/basic-info/employees/$employeeId': typeof DashboardBasicInfoEmployeesEmployeeIdIndexRoute
  '/customers/summary/$customerId': typeof DashboardCustomersSummaryCustomerIdIndexRoute
  '/customers/summary/$customerId/projects/$projectId': typeof DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute
  '/customers/summary/$customerId/projects/create': typeof DashboardCustomersSummaryCustomerIdProjectsCreateRoute
  '/customers/summary/$customerId/projects': typeof DashboardCustomersSummaryCustomerIdProjectsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/basic-info': typeof DashboardBasicInfoRouteRouteWithChildren
  '/_dashboard/customers': typeof DashboardCustomersRouteRouteWithChildren
  '/_dashboard/production': typeof DashboardProductionRouteRouteWithChildren
  '/_dashboard/warehouse': typeof DashboardWarehouseRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/basic-info/company-info': typeof DashboardBasicInfoCompanyInfoRoute
  '/_dashboard/customers/create': typeof DashboardCustomersCreateRoute
  '/_dashboard/warehouse/certificates': typeof DashboardWarehouseCertificatesRoute
  '/_dashboard/warehouse/consumed': typeof DashboardWarehouseConsumedRoute
  '/_dashboard/warehouse/orders': typeof DashboardWarehouseOrdersRoute
  '/_dashboard/warehouse/purchases': typeof DashboardWarehousePurchasesRoute
  '/_dashboard/warehouse/stocked': typeof DashboardWarehouseStockedRoute
  '/_dashboard/production/': typeof DashboardProductionIndexRoute
  '/_dashboard/basic-info/employees/create': typeof DashboardBasicInfoEmployeesCreateRoute
  '/_dashboard/basic-info/erp-permissions/app-machine-permissions': typeof DashboardBasicInfoErpPermissionsAppMachinePermissionsRoute
  '/_dashboard/basic-info/erp-permissions/department-members': typeof DashboardBasicInfoErpPermissionsDepartmentMembersRoute
  '/_dashboard/basic-info/erp-permissions/departments': typeof DashboardBasicInfoErpPermissionsDepartmentsRoute
  '/_dashboard/basic-info/erp-permissions/roles': typeof DashboardBasicInfoErpPermissionsRolesRoute
  '/_dashboard/basic-info/erp-permissions/users': typeof DashboardBasicInfoErpPermissionsUsersRoute
  '/_dashboard/production/$customerId/$projectId': typeof DashboardProductionCustomerIdProjectIdRoute
  '/_dashboard/basic-info/employees/': typeof DashboardBasicInfoEmployeesIndexRoute
  '/_dashboard/customers/summary/': typeof DashboardCustomersSummaryIndexRoute
  '/_dashboard/basic-info/employees/$employeeId/': typeof DashboardBasicInfoEmployeesEmployeeIdIndexRoute
  '/_dashboard/customers/summary/$customerId/': typeof DashboardCustomersSummaryCustomerIdIndexRoute
  '/_dashboard/customers/summary/$customerId/projects/$projectId': typeof DashboardCustomersSummaryCustomerIdProjectsProjectIdRoute
  '/_dashboard/customers/summary/$customerId/projects/create': typeof DashboardCustomersSummaryCustomerIdProjectsCreateRoute
  '/_dashboard/customers/summary/$customerId/projects/': typeof DashboardCustomersSummaryCustomerIdProjectsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/basic-info'
    | '/customers'
    | '/production'
    | '/warehouse'
    | '/'
    | '/basic-info/company-info'
    | '/customers/create'
    | '/warehouse/certificates'
    | '/warehouse/consumed'
    | '/warehouse/orders'
    | '/warehouse/purchases'
    | '/warehouse/stocked'
    | '/production/'
    | '/basic-info/employees/create'
    | '/basic-info/erp-permissions/app-machine-permissions'
    | '/basic-info/erp-permissions/department-members'
    | '/basic-info/erp-permissions/departments'
    | '/basic-info/erp-permissions/roles'
    | '/basic-info/erp-permissions/users'
    | '/production/$customerId/$projectId'
    | '/basic-info/employees'
    | '/customers/summary'
    | '/basic-info/employees/$employeeId'
    | '/customers/summary/$customerId'
    | '/customers/summary/$customerId/projects/$projectId'
    | '/customers/summary/$customerId/projects/create'
    | '/customers/summary/$customerId/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/basic-info'
    | '/customers'
    | '/warehouse'
    | '/'
    | '/basic-info/company-info'
    | '/customers/create'
    | '/warehouse/certificates'
    | '/warehouse/consumed'
    | '/warehouse/orders'
    | '/warehouse/purchases'
    | '/warehouse/stocked'
    | '/production'
    | '/basic-info/employees/create'
    | '/basic-info/erp-permissions/app-machine-permissions'
    | '/basic-info/erp-permissions/department-members'
    | '/basic-info/erp-permissions/departments'
    | '/basic-info/erp-permissions/roles'
    | '/basic-info/erp-permissions/users'
    | '/production/$customerId/$projectId'
    | '/basic-info/employees'
    | '/customers/summary'
    | '/basic-info/employees/$employeeId'
    | '/customers/summary/$customerId'
    | '/customers/summary/$customerId/projects/$projectId'
    | '/customers/summary/$customerId/projects/create'
    | '/customers/summary/$customerId/projects'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/basic-info'
    | '/_dashboard/customers'
    | '/_dashboard/production'
    | '/_dashboard/warehouse'
    | '/_dashboard/'
    | '/_dashboard/basic-info/company-info'
    | '/_dashboard/customers/create'
    | '/_dashboard/warehouse/certificates'
    | '/_dashboard/warehouse/consumed'
    | '/_dashboard/warehouse/orders'
    | '/_dashboard/warehouse/purchases'
    | '/_dashboard/warehouse/stocked'
    | '/_dashboard/production/'
    | '/_dashboard/basic-info/employees/create'
    | '/_dashboard/basic-info/erp-permissions/app-machine-permissions'
    | '/_dashboard/basic-info/erp-permissions/department-members'
    | '/_dashboard/basic-info/erp-permissions/departments'
    | '/_dashboard/basic-info/erp-permissions/roles'
    | '/_dashboard/basic-info/erp-permissions/users'
    | '/_dashboard/production/$customerId/$projectId'
    | '/_dashboard/basic-info/employees/'
    | '/_dashboard/customers/summary/'
    | '/_dashboard/basic-info/employees/$employeeId/'
    | '/_dashboard/customers/summary/$customerId/'
    | '/_dashboard/customers/summary/$customerId/projects/$projectId'
    | '/_dashboard/customers/summary/$customerId/projects/create'
    | '/_dashboard/customers/summary/$customerId/projects/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard",
        "/login"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard/route.tsx",
      "children": [
        "/_dashboard/basic-info",
        "/_dashboard/customers",
        "/_dashboard/production",
        "/_dashboard/warehouse",
        "/_dashboard/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_dashboard/basic-info": {
      "filePath": "_dashboard/basic-info/route.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/basic-info/company-info",
        "/_dashboard/basic-info/employees/create",
        "/_dashboard/basic-info/erp-permissions/app-machine-permissions",
        "/_dashboard/basic-info/erp-permissions/department-members",
        "/_dashboard/basic-info/erp-permissions/departments",
        "/_dashboard/basic-info/erp-permissions/roles",
        "/_dashboard/basic-info/erp-permissions/users",
        "/_dashboard/basic-info/employees/",
        "/_dashboard/basic-info/employees/$employeeId/"
      ]
    },
    "/_dashboard/customers": {
      "filePath": "_dashboard/customers/route.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/customers/create",
        "/_dashboard/customers/summary/",
        "/_dashboard/customers/summary/$customerId/",
        "/_dashboard/customers/summary/$customerId/projects/$projectId",
        "/_dashboard/customers/summary/$customerId/projects/create",
        "/_dashboard/customers/summary/$customerId/projects/"
      ]
    },
    "/_dashboard/production": {
      "filePath": "_dashboard/production/route.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/production/",
        "/_dashboard/production/$customerId/$projectId"
      ]
    },
    "/_dashboard/warehouse": {
      "filePath": "_dashboard/warehouse/route.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/warehouse/certificates",
        "/_dashboard/warehouse/consumed",
        "/_dashboard/warehouse/orders",
        "/_dashboard/warehouse/purchases",
        "/_dashboard/warehouse/stocked"
      ]
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/basic-info/company-info": {
      "filePath": "_dashboard/basic-info/company-info.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/customers/create": {
      "filePath": "_dashboard/customers/create.tsx",
      "parent": "/_dashboard/customers"
    },
    "/_dashboard/warehouse/certificates": {
      "filePath": "_dashboard/warehouse/certificates.tsx",
      "parent": "/_dashboard/warehouse"
    },
    "/_dashboard/warehouse/consumed": {
      "filePath": "_dashboard/warehouse/consumed.tsx",
      "parent": "/_dashboard/warehouse"
    },
    "/_dashboard/warehouse/orders": {
      "filePath": "_dashboard/warehouse/orders.tsx",
      "parent": "/_dashboard/warehouse"
    },
    "/_dashboard/warehouse/purchases": {
      "filePath": "_dashboard/warehouse/purchases.tsx",
      "parent": "/_dashboard/warehouse"
    },
    "/_dashboard/warehouse/stocked": {
      "filePath": "_dashboard/warehouse/stocked.tsx",
      "parent": "/_dashboard/warehouse"
    },
    "/_dashboard/production/": {
      "filePath": "_dashboard/production/index.tsx",
      "parent": "/_dashboard/production"
    },
    "/_dashboard/basic-info/employees/create": {
      "filePath": "_dashboard/basic-info/employees/create.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/basic-info/erp-permissions/app-machine-permissions": {
      "filePath": "_dashboard/basic-info/erp-permissions/app-machine-permissions.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/basic-info/erp-permissions/department-members": {
      "filePath": "_dashboard/basic-info/erp-permissions/department-members.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/basic-info/erp-permissions/departments": {
      "filePath": "_dashboard/basic-info/erp-permissions/departments.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/basic-info/erp-permissions/roles": {
      "filePath": "_dashboard/basic-info/erp-permissions/roles.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/basic-info/erp-permissions/users": {
      "filePath": "_dashboard/basic-info/erp-permissions/users.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/production/$customerId/$projectId": {
      "filePath": "_dashboard/production/$customerId/$projectId.tsx",
      "parent": "/_dashboard/production"
    },
    "/_dashboard/basic-info/employees/": {
      "filePath": "_dashboard/basic-info/employees/index.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/customers/summary/": {
      "filePath": "_dashboard/customers/summary/index.tsx",
      "parent": "/_dashboard/customers"
    },
    "/_dashboard/basic-info/employees/$employeeId/": {
      "filePath": "_dashboard/basic-info/employees/$employeeId/index.tsx",
      "parent": "/_dashboard/basic-info"
    },
    "/_dashboard/customers/summary/$customerId/": {
      "filePath": "_dashboard/customers/summary/$customerId/index.tsx",
      "parent": "/_dashboard/customers"
    },
    "/_dashboard/customers/summary/$customerId/projects/$projectId": {
      "filePath": "_dashboard/customers/summary/$customerId/projects/$projectId.tsx",
      "parent": "/_dashboard/customers"
    },
    "/_dashboard/customers/summary/$customerId/projects/create": {
      "filePath": "_dashboard/customers/summary/$customerId/projects/create.tsx",
      "parent": "/_dashboard/customers"
    },
    "/_dashboard/customers/summary/$customerId/projects/": {
      "filePath": "_dashboard/customers/summary/$customerId/projects/index.tsx",
      "parent": "/_dashboard/customers"
    }
  }
}
ROUTE_MANIFEST_END */
